name: "Build VimR nightly on tag"
on:
  push:
    tags:
      - 'neovim-nightly'

jobs:
  Build-universal:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Install brew packages
        run: |
          brew update >/dev/null
          brew upgrade
          brew install automake ninja coreutils
      - name: Build VimR
        run: |
          is_snapshot=true ./bin/set_new_versions.sh
          code_sign=false clean=true use_carthage_cache=false ./bin/build_nightly.sh
      - name: Replace artifact
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} ./build/Build/Products/ReleaseVimR-neovim-nightly-unsigned.tar.bz2 --clobber

