name: "VimR deps release on tag"
on:
  push:
    tags:
      - 'vimr-deps-*'

jobs:
  Build-universal:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install brew packages
        run: |
          brew update >/dev/null
          brew upgrade
          brew install automake coreutils pyenv pyenv-virtualenv
      - name: Set up Python env
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          
          pyenv install 3.9.7
          pyenv virtualenv 3.9.7 com.qvacua.VimR.bin
          
          pushd bin >/dev/null
            pip install -r requirements.txt
            python setup.py develop
          popd >/dev/null
      - name: Build deps
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          
          ./bin/build_deps.sh
      - name: Create release and upload artifact
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pushd bin/third_party >/dev/null
            tar cjf vimr-deps.tar.bz2 vimr-deps
            gh release create -p ${{ github.ref_name }}
            gh release upload ${{ github.ref_name }} vimr-deps.tar.bz2
          popd >/dev/null
      - uses: actions/upload-artifact@v2
        with:
          name: vimr-deps
          path: bin/third_party/vimr-deps
          if-no-files-found: error
          retention-days: 7
